const MARK_AS_READ = 'MARK_AS_READ'
const SET_TYPE_FILTER = 'SET_TYPE_FILTER'
const URGENT = 'URGENT'
const DEFAULT = 'DEFAULT'
FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS'

const NotificationTypeFilters = { URGENT, DEFAULT }

module.exports = { MARK_AS_READ, SET_TYPE_FILTER, NotificationTypeFilters, FETCH_NOTIFICATION_SUCCESS}
